# NREL Wave Hindacast Data Access Via rex

#### This notebook demonstrates basic usage of REsource eXtraciton tool (rex) with the National Renewable Energy Laboratory (NREL) West Coast Wave Hindcast dataset. The data is provided from Amazon Web Services using the HDF Group's Highly Scalable Data Service (HSDS).

#### For this example to work, the packages necessary can be installed via pip:

pip install -r requirements.txt

#### Next you'll need to configure h5pyd to access the data on HSDS:

hsconfigure

#### and enter at the prompt:

hs_endpoint = https://developer.nrel.gov/api/hsds   
hs_username = None   
hs_password = None   
hs_api_key = 3K3JQbjZmWctY0xmIfSYvYgtIcM3CN0cb1Y2w9bf    

#### The example API key here is for demonstation and is rate-limited per IP. To get your own API key, visit https://developer.nrel.gov/signup/

#### You can also add the above contents to a configuration file at ~/.hscfg

#### Finally, you can use Jupyter Notebook or Lab to view the example notebooks depending on your preference

In [1]:
from rex import WaveX
import pandas as pd

### Basic Usage

rex enables the efficient and scalable extraction, manipulation, and computation with NRELs flagship renewable resource datasets: the Wind Integration National Dataset (WIND Toolkit), and the National Solar Radiation Database (NSRDB). Development of functionality with the Wave Hindcast dataset is currently ongoing.

The Wave Hindcast Dataset is provided in annual .h5 files and currently spans the Western Coastal Region of the Lower 48 from 1979-2010.

Each year can be accessed from /nrel/us-wave/US_Wave_${year}.h5

To open the desired year of Wave Hindcast data server endpoint, username, password is found via a config file

In [6]:
waveFile = f'/nrel/US_wave/US_wave_1990.h5'

In [8]:
# quick View of metadata, time_index, and coordinates 

with WaveX(waveFile, hsds=True) as waves:
    meta = waves.meta          ## meta is an object that contains location information for each data point
    print("meta =", meta)
    time_index = waves.time_index # time_index contains all of the years within the file
    print("time_index =",time_index)
    coordinates = waves.coordinates # coordinates contains all the lat/lon pars within the dataset
    print("coordinates =",coordinates)

meta =         water_depth   latitude   longitude  distance_to_shore  timezone  \
0          6.718400  48.864101 -125.386002         993.098145        -8
1         28.699100  48.841801 -125.445999        5096.523438        -8
2         49.457100  48.819302 -125.503998        6850.421387        -8
3         72.204498  48.797199 -125.563004       10784.603516        -8
4         92.086197  48.773998 -125.622002       15433.410156        -8
...             ...        ...         ...                ...       ...
699899     0.100000  37.463200 -122.027000          91.001328        -8
699900   -99.000000  37.461700 -122.027000           0.000000        -8
699901     0.100000  37.463100 -122.026001          35.939137        -8
699902   -99.000000  37.461498 -122.026001           0.000000        -8
699903     0.100000  37.461399 -122.025002           0.000000        -8

       jurisdiction
0            Canada
1            Canada
2            Canada
3            Canada
4            Canada
...             ...
699899   California
699900   California
699901   California
699902   California
699903   California

[699904 rows x 6 columns]
time_index = DatetimeIndex(['1990-01-01 00:00:00+00:00', '1990-01-01 03:00:00+00:00',
               '1990-01-01 06:00:00+00:00', '1990-01-01 09:00:00+00:00',
               '1990-01-01 12:00:00+00:00', '1990-01-01 15:00:00+00:00',
               '1990-01-01 18:00:00+00:00', '1990-01-01 21:00:00+00:00',
               '1990-01-02 00:00:00+00:00', '1990-01-02 03:00:00+00:00',
               ...
               '1990-12-30 18:00:00+00:00', '1990-12-30 21:00:00+00:00',
               '1990-12-31 00:00:00+00:00', '1990-12-31 03:00:00+00:00',
               '1990-12-31 06:00:00+00:00', '1990-12-31 09:00:00+00:00',
               '1990-12-31 12:00:00+00:00', '1990-12-31 15:00:00+00:00',
               '1990-12-31 18:00:00+00:00', '1990-12-31 21:00:00+00:00'],
              dtype='datetime64[ns, UTC]', length=2920, freq=None)
coordinates = [[  48.8641 -125.386 ]
 [  48.8418 -125.446 ]
 [  48.8193 -125.504 ]
 ...
 [  37.4631 -122.026 ]
 [  37.4615 -122.026 ]
 [  37.4614 -122.025 ]]
keys = WaveX for /nrel/US_wave/US_wave_1990.h5

## Dataset variables

Each year of hindcast data contains the following datasets:

- directionality_coefficient
- energy_period
- maximum_energy_direction
- mean_absolute_period
- mean_zero-crossing_period
- omni-directional_wave_power
- peak_period
- significant_wave_height
- spectral_width
- water_depth

Each dataset is structured with a time index and a lat/lon coordinate
in the form: ('time_index','coordinates').

# Basic Usage

The following examples illustrate basic spatial and timeseries slicing techniques for the West Coast Wave Hindcast dataset, along with simple statistical analysis.

## Accessing the Datasets 

Below are some example of how you can access data using the rex Python package.
Datasets are returned as Pandas objects. See the Pandas [documentation](https://pandas.pydata.org/pandas-docs/stable/) 
for more information about working with Pandas objects.

### Extracting data from a single site
A single lat/lon pair can be given to extract data nearest to that location.

In [9]:
# Extract the timeseries of significant_wave_height closest to a coordinate pair

with WaveX(waveFile, hsds=True) as waves:
    lat_lon = (44.624076,-124.280097)
    parameters = 'significant_wave_height'
    swh_single = waves.get_lat_lon_df(parameters, lat_lon)
swh_single

                           significant_wave_height
time_index
1990-01-01 00:00:00+00:00                  4.12372
1990-01-01 03:00:00+00:00                  4.08943
1990-01-01 06:00:00+00:00                  4.02213
1990-01-01 09:00:00+00:00                  4.04348
1990-01-01 12:00:00+00:00                  4.20646
...                                            ...
1990-12-31 09:00:00+00:00                  1.86854
1990-12-31 12:00:00+00:00                  2.27088
1990-12-31 15:00:00+00:00                  2.45501
1990-12-31 18:00:00+00:00                  2.48654
1990-12-31 21:00:00+00:00                  2.47437

[2920 rows x 1 columns]

### Extracting data from multiple sites
A list of latitude/longitude pairs can be passed to extract data from multiple sites

In [15]:
with WaveX(waveFile, hsds=True) as waves:
    lat_lon = [(44.624076,-124.280097),(43.489171,-125.152137)] # set lat_lon to a list of lat/lon pairs
    parameters = 'significant_wave_height'
    swh_multi = waves.get_lat_lon_df(parameters, lat_lon)
swh_multi

                            413889   296246
time_index
1990-01-01 00:00:00+00:00  4.12372  4.04668
1990-01-01 03:00:00+00:00  4.08943  4.00852
1990-01-01 06:00:00+00:00  4.02213  3.99011
1990-01-01 09:00:00+00:00  4.04348  4.07808
1990-01-01 12:00:00+00:00  4.20646  4.31954
...                            ...      ...
1990-12-31 09:00:00+00:00  1.86854  1.43289
1990-12-31 12:00:00+00:00  2.27088  1.78697
1990-12-31 15:00:00+00:00  2.45501  2.07993
1990-12-31 18:00:00+00:00  2.48654  2.21332
1990-12-31 21:00:00+00:00  2.47437  2.26290

[2920 rows x 2 columns]

### Extract all data within a specified region 

Data can be extracted from a particular region based on jurisdiction regions found in the meta object.

In [18]:
with WaveX(waveFile, hsds=True) as waves:
    region = 'Oregon'                     # Specify Oregon as the jurisdiction region 
    region_col = 'jurisdiction'           # specify jurisdiction as the meta object column you are searching against
    variables = 'significant_wave_height'
    swh_map = waves.get_region_df(variables, region, region_col=region_col)
swh_map

,324547,326368,326369,326370,326371,328202,328203,328204,328205,328206,...,687050,687051,687052,687053,687054,687180,687181,687182,687183,687184
time_index,,,,,,,,,,,,,,,,,,,,,
1990-01-01 00:00:00+00:00,4.14059,4.12563,4.14632,4.06618,3.97402,4.09801,4.13695,4.07028,3.99171,3.98505,...,0.00858,0.00642,0.00430,0.00247,0.00073,0.00422,0.00605,0.00417,0.00233,0.00057
1990-01-01 03:00:00+00:00,4.09281,4.07890,4.09882,4.01493,3.91829,4.05022,4.08826,4.01886,3.93864,3.92987,...,0.00632,0.00498,0.00351,0.00217,0.00047,0.00316,0.00473,0.00337,0.00200,0.00036
1990-01-01 06:00:00+00:00,4.00169,3.99055,4.00960,3.92331,3.81813,3.96471,4.00149,3.92981,3.84585,3.82933,...,0.00436,0.00353,0.00254,0.00160,0.00032,0.00219,0.00338,0.00245,0.00148,0.00025
1990-01-01 09:00:00+00:00,3.94321,3.93687,3.95479,3.86283,3.74373,3.91353,3.94893,3.87309,3.78036,3.75405,...,0.00200,0.00149,0.00098,0.00053,0.00021,0.00095,0.00138,0.00094,0.00050,0.00017
1990-01-01 12:00:00+00:00,4.00260,3.99913,4.01710,3.92068,3.77794,3.98026,4.01336,3.93564,3.82435,3.78663,...,0.00043,0.00030,0.00019,0.00009,0.00004,0.00020,0.00027,0.00018,0.00008,0.00003
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1990-12-31 09:00:00+00:00,2.46143,2.50435,2.47441,2.44698,2.46655,2.51205,2.47991,2.46354,2.41339,2.45670,...,0.00601,0.00556,0.00442,0.00311,0.00019,0.00301,0.00471,0.00355,0.00231,0.00014
1990-12-31 12:00:00+00:00,2.69044,2.72542,2.69965,2.67293,2.69581,2.72969,2.70136,2.68576,2.63687,2.68450,...,0.01068,0.00925,0.00705,0.00477,0.00051,0.00563,0.00858,0.00638,0.00407,0.00038
1990-12-31 15:00:00+00:00,2.65428,2.68488,2.66136,2.63648,2.65523,2.69056,2.66293,2.64791,2.59698,2.64515,...,0.00606,0.00523,0.00396,0.00264,0.00033,0.00310,0.00483,0.00357,0.00225,0.00025
1990-12-31 18:00:00+00:00,2.60624,2.63802,2.61414,2.58937,2.59963,2.64684,2.61752,2.60231,2.54657,2.58861,...,0.00597,0.00515,0.00389,0.00259,0.00032,0.00307,0.00480,0.00355,0.00224,0.00024
1990-12-31 21:00:00+00:00,2.57874,2.61324,2.58841,2.56208,2.56536,2.62467,2.59370,2.57747,2.51702,2.55350,...,0.00481,0.00406,0.00301,0.00196,0.00030,0.00243,0.00380,0.00278,0.00172,0.00023

### Extracting Data over Multiple Years

Data can be extracted over a number of years and concatonated directly using rex functionality.

The new multi-year object has the same functionality as a single year dataset. The datasets

In [31]:
from rex import MultiYearWaveX # Yearly concatonation requires the MultiYearResource function

In [32]:
multi_year_waves = f'/nrel/US_wave/US_wave_199*.h5' # file names ccan now accept Wildcards to specify which files to load

In [30]:

with MultiYearWaveX(multi_year_waves,hsds=True) as mYears:
    lat_lon = (44.624076,-124.280097)
    parameters = 'significant_wave_height'
    swh_single = mYears.get_lat_lon_df(parameters, lat_lon)
swh_single

                           significant_wave_height
time_index
1990-01-01 00:00:00+00:00                  4.12372
1990-01-01 03:00:00+00:00                  4.08943
1990-01-01 06:00:00+00:00                  4.02213
1990-01-01 09:00:00+00:00                  4.04348
1990-01-01 12:00:00+00:00                  4.20646
...                                            ...
1999-12-31 09:00:00+00:00                  1.07751
1999-12-31 12:00:00+00:00                  1.04957
1999-12-31 15:00:00+00:00                  1.03966
1999-12-31 18:00:00+00:00                  1.08590
1999-12-31 21:00:00+00:00                  1.21570

[29210 rows x 1 columns]

In [ ]:
with MultiYearWaveX(multi_year_waves, hsds=True) as waves:
    lat_lon = [(44.624076,-124.280097),(43.489171,-125.152137)] # set lat_lon to a list of lat/lon pairs
    parameters = 'significant_wave_height'
    swh_multi = waves.get_lat_lon_df(parameters, lat_lon)
swh_multi

## Integration with MHKit

--

In [2]:
# Hacky way to import a local version of mhkit during development

import sys
sys.path.insert(1, '/mnt/c/Users/abharath/Documents/Projects/MHKit/MHKiT-Python/')

from mhkit.wave import io

In [3]:

single_year_waves = f'/nrel/US_wave/US_wave_1995.h5'
lat_lon = (44.624076,-124.280097)
parameters = 'significant_wave_height'

wave_singleYear = io.read_US_wave_dataset(single_year_waves,parameters,lat_lon)

wave_singleYear

time_index
1995-01-01 00:00:00+00:00    2.35354
1995-01-01 03:00:00+00:00    2.39468
1995-01-01 06:00:00+00:00    2.45756
1995-01-01 09:00:00+00:00    2.55913
1995-01-01 12:00:00+00:00    2.66992
                              ...
1995-12-31 09:00:00+00:00    4.83878
1995-12-31 12:00:00+00:00    4.65337
1995-12-31 15:00:00+00:00    4.40868
1995-12-31 18:00:00+00:00    4.47692
1995-12-31 21:00:00+00:00    4.59119
Name: significant_wave_height, Length: 2920, dtype: float32

In [ ]:

single_year_waves = f'/nrel/US_wave/US_wave_1995.h5'
lat_lon = [(44.624076,-124.280097),(43.489171,-125.152137)]
parameters = 'significant_wave_height'

wave_multiLocal = io.read_US_wave_dataset(single_year_waves,parameters,lat_lon)

wave_multiLocal

In [2]:

multi_year_waves = f'/nrel/US_wave/US_wave_199*.h5'
lat_lon = (44.624076,-124.280097)
parameters = 'significant_wave_height'

wave_multiYear = io.read_US_wave_dataset(multi_year_waves,parameters,lat_lon)

wave_multiYear

#### Calculations with MHKiT

Further examples with MHKiT

In [4]:
from numpy.random import seed, normal

owp = 'omni-directional_wave_power'
J = io.read_US_wave_dataset(single_year_waves,owp,lat_lon)

# Set the random seed, to reproduce results
seed(1)                                               
# Generate random power values
P = pd.Series(normal(200, 40, J.shape[0]),index = J.index)

In [9]:
from mhkit.wave.performance import wave_energy_flux_matrix, capture_length, capture_length_matrix, power_matrix
from numpy import arange

Te = io.read_US_wave_dataset(single_year_waves,'energy_period',lat_lon)
Hm0 = io.read_US_wave_dataset(single_year_waves,'significant_wave_height',lat_lon)

# Calculate capture length
L = capture_length(P, J) 

# Generate bins for Hm0 and Te, input format (start, stop, step_size)
Hm0_bins = arange(0, Hm0.values.max() + .5, .5)    
Te_bins = arange(0, Te.values.max() + 1, 1)

# Create capture length matrix using a mean
LM = capture_length_matrix(Hm0, Te, L, 'mean', Hm0_bins, Te_bins)
# Create wave energy flux matrix using mean
JM = wave_energy_flux_matrix(Hm0, Te, J, 'mean', Hm0_bins, Te_bins)

# Create power matrix using mean
PM = power_matrix(LM, JM)

In [16]:
#%matplotlib widget
import matplotlib.pyplot as plt
from mhkit.wave.graphics import plot_matrix


# Plot the Plot mean matrix
ax = plot_matrix(PM)
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous â€¦